"""empty message

Revision ID: 140c16478e4b
Revises: 
Create Date: 2018-10-17 12:34:03.315273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '140c16478e4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acs5_detailed_ed_attain25yrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('censustractid', sa.String(length=10), nullable=True),
    sa.Column('censustract', sa.String(length=10), nullable=True),
    sa.Column('educational_attainment', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acs5_detailed_field_of_bachelor_degree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('censustractid', sa.String(length=10), nullable=True),
    sa.Column('censustract', sa.String(length=10), nullable=True),
    sa.Column('field_of_bachelor_degree', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acs5_ed_attain_by_employment25yrs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('censustractid', sa.String(length=10), nullable=True),
    sa.Column('censustract', sa.String(length=10), nullable=True),
    sa.Column('employment_status_25_64_years', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acs5_household_income_by_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('censustractid', sa.String(length=10), nullable=True),
    sa.Column('censustract', sa.String(length=10), nullable=True),
    sa.Column('householdincome', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acs5_place_of_birth_by_citizenship',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('censustractid', sa.String(length=10), nullable=True),
    sa.Column('censustract', sa.String(length=10), nullable=True),
    sa.Column('placeofbirth', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acs5_population_age_by_race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('censustractid', sa.String(length=10), nullable=True),
    sa.Column('censustract', sa.String(length=10), nullable=True),
    sa.Column('agegroup', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('acs5_school_enrollment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('censustractid', sa.String(length=10), nullable=True),
    sa.Column('censustract', sa.String(length=10), nullable=True),
    sa.Column('schoolenrollment', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('free_reduced_lunch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ncesid', sa.String(length=10), nullable=True),
    sa.Column('numReducedLunch', sa.Integer(), nullable=True),
    sa.Column('numFreeLunch', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('median_household_income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('censustractid', sa.String(length=10), nullable=True),
    sa.Column('censustract', sa.String(length=10), nullable=True),
    sa.Column('household_income', sa.String(length=10), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ncesid', sa.String(length=10), nullable=True),
    sa.Column('totalstudent', sa.Integer(), nullable=True),
    sa.Column('stype', sa.String(length=20), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_demographics')
    op.drop_table('median_household_income')
    op.drop_table('free_reduced_lunch')
    op.drop_table('acs5_school_enrollment')
    op.drop_table('acs5_population_age_by_race')
    op.drop_table('acs5_place_of_birth_by_citizenship')
    op.drop_table('acs5_household_income_by_race')
    op.drop_table('acs5_ed_attain_by_employment25yrs')
    op.drop_table('acs5_detailed_field_of_bachelor_degree')
    op.drop_table('acs5_detailed_ed_attain25yrs')
    # ### end Alembic commands ###
